# fly.toml app configuration file generated for se-bridge-morning-feather-8426 on 2026-04-10T10:04:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'se-bridge-morning-feather-8426'
primary_region = 'ams'

[build]

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
