using Newtonsoft.Json.Linq;
using OBSWebsocketDotNet.Types;
using SpekkieTwitchBot.Models.OBS.Communication;
using SpekkieTwitchBot.Models.OBS.Events;
using Monitor = OBSWebsocketDotNet.Types.Monitor;
using ObsStats = SpekkieTwitchBot.Models.OBS.Types.ObsStats;
using SceneBasicInfo = SpekkieTwitchBot.Models.OBS.Types.SceneBasicInfo;
using GetSceneListInfo = SpekkieTwitchBot.Models.OBS.Types.GetSceneListInfo;
using TransitionOverrideInfo = SpekkieTwitchBot.Models.OBS.Types.TransitionOverrideInfo;
using FilterSettings = SpekkieTwitchBot.Models.OBS.Types.FilterSettings;
using GetProfileListInfo = SpekkieTwitchBot.Models.OBS.Types.GetProfileListInfo;
using GetTransitionListInfo = SpekkieTwitchBot.Models.OBS.Types.GetTransitionListInfo;
using InputBasicInfo = SpekkieTwitchBot.Models.OBS.Types.InputBasicInfo;
using InputSettings = SpekkieTwitchBot.Models.OBS.Types.InputSettings;
using KeyModifier = SpekkieTwitchBot.Models.OBS.Enum.KeyModifier;
using MediaInputStatus = SpekkieTwitchBot.Models.OBS.Types.MediaInputStatus;
using RecordingStatus = SpekkieTwitchBot.Models.OBS.Types.RecordingStatus;
using OBSHotKey = SpekkieTwitchBot.Models.OBS.Enum.OBSHotkey;
using ObsVersion = SpekkieTwitchBot.Models.OBS.Types.ObsVersion;
using ObsVideoSettings = SpekkieTwitchBot.Models.OBS.Types.ObsVideoSettings;
using OutputStatus = SpekkieTwitchBot.Models.OBS.Types.OutputStatus;
using SceneItemDetails = SpekkieTwitchBot.Models.OBS.Types.SceneItemDetails;
using SceneItemTransformInfo = SpekkieTwitchBot.Models.OBS.Types.SceneItemTransformInfo;
using SourceActiveInfo = SpekkieTwitchBot.Models.OBS.Types.SourceActiveInfo;
using SourceTracks = SpekkieTwitchBot.Models.OBS.Types.SourceTracks;
using StreamingService = SpekkieTwitchBot.Models.OBS.Types.StreamingService;
using TransitionSettings = SpekkieTwitchBot.Models.OBS.Types.TransitionSettings;
using VirtualCamStatus = SpekkieTwitchBot.Models.OBS.Types.VirtualCamStatus;
using VolumeInfo = SpekkieTwitchBot.Models.OBS.Types.VolumeInfo;

namespace SpekkieTwitchBot.Models.OBS.Interface;

public interface IOBSWebsocket
{
    #region Properties
    TimeSpan WSTimeout { get; set; }
    bool IsConnected { get; }

    #endregion

    #region Requests
    Types.ObsVideoSettings GetVideoSettings();
    string SaveSourceScreenshot(string sourceName, string imageFormat, string imageFilePath, int imageWidth = -1, int imageHeight = -1, int imageCompressionQuality = -1);
    string SaveSourceScreenshot(string sourceName, string imageFormat, string imageFilePath);
    void TriggerHotkeyByName(string hotkeyName);
    void TriggerHotkeyByKeySequence(OBSHotKey keyId, KeyModifier keyModifier = KeyModifier.None);
    string GetCurrentProgramScene();
    void SetCurrentProgramScene(string sceneName);
    ObsStats GetStats();
    List<SceneBasicInfo> ListScenes();
    GetSceneListInfo GetSceneList();
    TransitionOverrideInfo GetSceneSceneTransitionOverride(string sceneName);
    void SetSceneSceneTransitionOverride(string sceneName, string transitionName, int transitionDuration = -1);
    void SetTBarPosition(double position, bool release = true);
    void SetSourceFilterSettings(string sourceName, string filterName, JObject filterSettings, bool overlay = false);
    void SetSourceFilterSettings(string sourceName, string filterName, FilterSettings filterSettings, bool overlay = false);
    void SetSourceFilterEnabled(string sourceName, string filterName, bool filterEnabled);
    List<FilterSettings> GetSourceFilterList(string sourceName);
    FilterSettings GetSourceFilter(string sourceName, string filterName);
    bool RemoveSourceFilter(string sourceName, string filterName);
    void CreateSourceFilter(string sourceName, string filterName, string filterKind, JObject filterSettings);
    void CreateSourceFilter(string sourceName, string filterName, string filterKind, FilterSettings filterSettings);
    bool ToggleStream();
    void ToggleRecord();
    OutputStatus GetStreamStatus();
    TransitionSettings GetCurrentSceneTransition();
    void SetCurrentSceneTransition(string transitionName);
    void SetCurrentSceneTransitionDuration(int transitionDuration);
    void SetCurrentSceneTransitionSettings(JObject transitionSettings, bool overlay);
    void SetInputVolume(string inputName, float inputVolume, bool inputVolumeDb = false);
    VolumeInfo GetInputVolume(string inputName);
    bool GetInputMute(string inputName);
    void SetInputMute(string inputName, bool inputMuted);
    void ToggleInputMute(string inputName);
    void SetSceneItemTransform(string sceneName, int sceneItemId, JObject sceneItemTransform);

    void SetSceneItemTransform(string sceneName, int sceneItemId, SceneItemTransformInfo sceneItemTransform);
    void SetCurrentSceneCollection(string sceneCollectionName);
    string GetCurrentSceneCollection();
    List<string> GetSceneCollectionList();
    void SetCurrentProfile(string profileName);
    GetProfileListInfo GetProfileList();
    void StartStream();
    void StopStream();
    void StartRecord();
    string StopRecord();
    void PauseRecord();
    void ResumeRecord();
    string GetRecordDirectory();
    RecordingStatus GetRecordStatus();
    bool GetReplayBufferStatus();
    GetTransitionListInfo GetSceneTransitionList();
    bool GetStudioModeEnabled();
    void SetStudioModeEnabled(bool studioModeEnabled);
    string GetCurrentPreviewScene();
    void SetCurrentPreviewScene(string sceneName);
    void SetCurrentPreviewScene(ObsScene previewScene);
    void TriggerStudioModeTransition();
    void ToggleReplayBuffer();
    void StartReplayBuffer();
    void StopReplayBuffer();
    void SaveReplayBuffer();
    void SetInputAudioSyncOffset(string inputName, int inputAudioSyncOffset);
    int GetInputAudioSyncOffset(string inputName);
    void RemoveSceneItem(string sceneName, int sceneItemId);
    void SendStreamCaption(string captionText);
    void DuplicateSceneItem(string sceneName, int sceneItemId, string destinationSceneName = null);
    Dictionary<string, string> GetSpecialInputs();
    void SetStreamServiceSettings(StreamingService service);
    StreamingService GetStreamServiceSettings();
    string GetInputAudioMonitorType(string inputName);
    void SetInputAudioMonitorType(string inputName, string monitorType);
    void BroadcastCustomEvent(JObject eventData);
    void SetMediaInputCursor(string inputName, int mediaCursor);
    void OffsetMediaInputCursor(string inputName, int mediaCursorOffset);
    int CreateInput(string sceneName, string inputName, string inputKind, JObject inputSettings, bool? sceneItemEnabled);
    JObject GetInputDefaultSettings(string inputKind);
    List<SceneItemDetails> GetSceneItemList(string sceneName);
    int CreateSceneItem(string sceneName, string sourceName, bool sceneItemEnabled = true);
    void CreateScene(string sceneName);
    SourceTracks GetInputAudioTracks(string inputName);
    void SetInputAudioTracks(string inputName, JObject inputAudioTracks);
    void SetInputAudioTracks(string inputName, SourceTracks inputAudioTracks);
    SourceActiveInfo GetSourceActive(string sourceName);
    VirtualCamStatus GetVirtualCamStatus();
    void StartVirtualCam();
    void StopVirtualCam();
    Types.VirtualCamStatus ToggleVirtualCam();
    JObject GetPersistentData(string realm, string slotName);
    void SetPersistentData(string realm, string slotName, JObject slotValue);
    void CreateSceneCollection(string sceneCollectionName);
    void CreateProfile(string profileName);
    void RemoveProfile(string profileName);
    JObject GetProfileParameter(string parameterCategory, string parameterName); 
    void SetProfileParameter(string parameterCategory, string parameterName, string parameterValue);
    void SetVideoSettings(ObsVideoSettings obsVideoSettings);
    JObject GetSourceFilterDefaultSettings(string filterKind);
    void SetSourceFilterName(string sourceName, string filterName, string newFilterName);
    void SetSourceFilterIndex(string sourceName, string filterName, int filterIndex);
    ObsVersion GetVersion();
    JObject CallVendorRequest(string vendorName, string requestType, JObject requestData = null);
    List<string> GetHotkeyList();
    void Sleep(int sleepMillis, int sleepFrames);
    List<InputBasicInfo> GetInputList(string inputKind = null);
    List<string> GetInputKindList(bool unversioned = false);
    void RemoveInput(string inputName);
    void SetInputName(string inputName, string newInputName);
    InputSettings GetInputSettings(string inputName);
    void SetInputSettings(InputSettings inputSettings, bool overlay = true);
    void SetInputSettings(string inputName, JObject inputSettings, bool overlay = true);
    double GetInputAudioBalance(string inputName);
    void SetInputAudioBalance(string inputName, double inputAudioBalance); 
    List<JObject> GetInputPropertiesListPropertyItems(string inputName, string propertyName);
    void PressInputPropertiesButton(string inputName, string propertyName);
    MediaInputStatus GetMediaInputStatus(string inputName);
    void TriggerMediaInputAction(string inputName, string mediaAction);
    string GetLastReplayBufferReplay();
    void ToggleRecordPause();
    List<JObject> GetGroupSceneItemList(string sceneName);
    int GetSceneItemId(string sceneName, string sourceName, int searchOffset);
    SceneItemTransformInfo GetSceneItemTransform(string sceneName, int sceneItemId);
    JObject GetSceneItemTransformRaw(string sceneName, int sceneItemId);
    bool GetSceneItemEnabled(string sceneName, int sceneItemId);
    void SetSceneItemEnabled(string sceneName, int sceneItemId, bool sceneItemEnabled);
    bool GetSceneItemLocked(string sceneName, int sceneItemId);
    void SetSceneItemLocked(string sceneName, int sceneItemId, bool sceneItemLocked);
    int GetSceneItemIndex(string sceneName, int sceneItemId);
    void SetSceneItemIndex(string sceneName, int sceneItemId, int sceneItemIndex);
    string GetSceneItemBlendMode(string sceneName, int sceneItemId);
    void SetSceneItemBlendMode(string sceneName, int sceneItemId, string sceneItemBlendMode);
    List<string> GetGroupList();
    void RemoveScene(string sceneName);
    void SetSceneName(string sceneName, string newSceneName);
    string GetSourceScreenshot(string sourceName, string imageFormat, int imageWidth = -1, int imageHeight = -1, int imageCompressionQuality = -1);
    List<string> GetTransitionKindList();
    double GetCurrentSceneTransitionCursor();
    void OpenInputPropertiesDialog(string inputName);
    void OpenInputFiltersDialog(string inputName);

    void OpenInputInteractDialog(string inputName);
    List<Types.Monitor> GetMonitorList();

    [Obsolete("Please use ConnectAsync, this function will be removed in the next version")]
    void Connect(string url, string password);
    void ConnectAsync(string url, string password);
    void Disconnect();
    JObject SendRequest(string requestType, JObject additionalFields = null);
    OBSAuthInfo GetAuthInfo();

    #endregion

    #region Events

    event EventHandler<ProgramSceneChangedEventArgs> CurrentProgramSceneChanged;
    event EventHandler<SceneListChangedEventArgs> SceneListChanged;
    event EventHandler<SceneItemListReindexedEventArgs> SceneItemListReindexed;
    event EventHandler<SceneItemCreatedEventArgs> SceneItemCreated;
    event EventHandler<SceneItemRemovedEventArgs> SceneItemRemoved;
    event EventHandler<SceneItemEnableStateChangedEventArgs> SceneItemEnableStateChanged;
    event EventHandler<SceneItemLockStateChangedEventArgs> SceneItemLockStateChanged;
    event EventHandler<CurrentSceneCollectionChangedEventArgs> CurrentSceneCollectionChanged;
    event EventHandler<SceneCollectionListChangedEventArgs> SceneCollectionListChanged;
    event EventHandler<CurrentSceneTransitionChangedEventArgs> CurrentSceneTransitionChanged;
    event EventHandler<CurrentSceneTransitionDurationChangedEventArgs> CurrentSceneTransitionDurationChanged;
    event EventHandler<SceneTransitionStartedEventArgs> SceneTransitionStarted;
    event EventHandler<SceneTransitionEndedEventArgs> SceneTransitionEnded;
    event EventHandler<SceneTransitionVideoEndedEventArgs> SceneTransitionVideoEnded;
    event EventHandler<CurrentProfileChangedEventArgs> CurrentProfileChanged;
    event EventHandler<ProfileListChangedEventArgs> ProfileListChanged;
    event EventHandler<StreamStateChangedEventArgs>? StreamStateChanged;
    event EventHandler<RecordStateChangedEventArgs> RecordStateChanged;
    event EventHandler<ReplayBufferStateChangedEventArgs> ReplayBufferStateChanged;
    event EventHandler<CurrentPreviewSceneChangedEventArgs> CurrentPreviewSceneChanged;
    event EventHandler<StudioModeStateChangedEventArgs> StudioModeStateChanged;
    event EventHandler ExitStarted;
    event EventHandler Connected;
    event EventHandler<ObsDisconnectionInfo> Disconnected;
    event EventHandler<SceneItemSelectedEventArgs> SceneItemSelected;
    event EventHandler<SceneItemTransformEventArgs> SceneItemTransformChanged;
    event EventHandler<InputAudioSyncOffsetChangedEventArgs> InputAudioSyncOffsetChanged;
    event EventHandler<SourceFilterCreatedEventArgs> SourceFilterCreated;
    event EventHandler<SourceFilterRemovedEventArgs> SourceFilterRemoved;
    event EventHandler<SourceFilterListReindexedEventArgs> SourceFilterListReindexed;
    event EventHandler<SourceFilterEnableStateChangedEventArgs> SourceFilterEnableStateChanged;
    event EventHandler<InputMuteStateChangedEventArgs> InputMuteStateChanged;
    event EventHandler<InputVolumeChangedEventArgs> InputVolumeChanged;
    event EventHandler<VendorEventArgs> VendorEvent;
    event EventHandler<MediaInputPlaybackEndedEventArgs> MediaInputPlaybackEnded;
    event EventHandler<MediaInputPlaybackStartedEventArgs> MediaInputPlaybackStarted;
    event EventHandler<MediaInputActionTriggeredEventArgs> MediaInputActionTriggered;
    event EventHandler<VirtualcamStateChangedEventArgs> VirtualcamStateChanged;
    event EventHandler<CurrentSceneCollectionChangingEventArgs> CurrentSceneCollectionChanging;
    event EventHandler<CurrentProfileChangingEventArgs> CurrentProfileChanging;
    event EventHandler<SourceFilterNameChangedEventArgs> SourceFilterNameChanged;
    event EventHandler<InputCreatedEventArgs> InputCreated;
    event EventHandler<InputRemovedEventArgs> InputRemoved;
    event EventHandler<InputNameChangedEventArgs> InputNameChanged;
    event EventHandler<InputActiveStateChangedEventArgs> InputActiveStateChanged;
    event EventHandler<InputShowStateChangedEventArgs> InputShowStateChanged; 
    event EventHandler<InputAudioBalanceChangedEventArgs> InputAudioBalanceChanged;
    event EventHandler<InputAudioTracksChangedEventArgs> InputAudioTracksChanged;
    event EventHandler<InputAudioMonitorTypeChangedEventArgs> InputAudioMonitorTypeChanged;
    event EventHandler<InputVolumeMetersEventArgs> InputVolumeMeters;
    event EventHandler<ReplayBufferSavedEventArgs> ReplayBufferSaved;
    event EventHandler<SceneCreatedEventArgs> SceneCreated;
    event EventHandler<SceneRemovedEventArgs> SceneRemoved;
    event EventHandler<SceneNameChangedEventArgs> SceneNameChanged;

    #endregion
}